
<!doctype html>
<html lang="en">

  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!-- Customized CSS -->
    <link rel="stylesheet" href="public/css/style.css">

  
    <!-- Bootstrap 4 Icon Set -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css"  crossorigin="anonymous">

    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>


    <title>
        Hello Insly!
    </title>
    
  </head>

  <body>

  <header>
      <!-- Fixed navbar -->
      <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        
        <div class="navbar-brand"><i class="fas fa-tasks"></i> Insly Developer Test</div>
        
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarCollapse">
          
          <ul class="navbar-nav mr-auto">
            
            <li class="nav-item ">
              <a class="nav-link" href="?action=task1"><i class="fas fa-angle-right"></i> Task 1 </a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="?action=task2"><i class="fas fa-angle-right"></i> Task 2</a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="?action=task3"><i class="fas fa-angle-right"></i> Task 3</a>
            </li>
            
          </ul>
          
        </div>
      </nav>
  </header>




    <!-- All the contents goes here -->
    <?= $this->content; ?>
            
  
    

    <!-- Popper.js first, then Bootstrap JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    

    <!-- Timezone JS -->
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jstimezonedetect/1.0.4/jstz.min.js"></script>
    <script type="text/javascript">
      $(document).ready(function()
      {
        var tz = jstz.determine(); 
        var timezone = tz.name(); 
        document.getElementById("timezone").value = timezone;
      });
    
    </script>
  </body>
</html>