 <main role="main" class="container">
    
	<h1 class="mt-5 taskContainer"> Task 3 - <small>Store employee data</small></h1>
    	
    <div class="row">
        <div class="col-md-2">
            <a href="?action=task3" class="btn btn-primary btn-xs pull-right"><b>+</b> Employee List</a>
        </div>
        <div class="col-md-2">
            <a href="?action=task3add" class="btn btn-primary btn-xs pull-right"><b>+</b> Add new employee</a>
        </div>
    </div>

    <h5 class="mt-5 "> Employee Detail</h5>
    <div class="row">
        <div class="col-md-2">
            <a href="?action=employee&id=<?php echo $data['employee']['id']?>&lang=en" class="btn  btn-xs pull-right"> <img src="img/en.svg" style="width:50px"> English</a>
        </div>
        <div class="col-md-2">
            <a href="?action=employee&id=<?php echo $data['employee']['id']?>&lang=es" class="btn btn-xs pull-right"> <img src="img/es.svg" style="width:50px"> Spain</a>
        </div>
        <div class="col-md-2">
            <a href="?action=employee&id=<?php echo $data['employee']['id']?>&lang=fr" class="btn  btn-xs pull-right"> <img src="img/fr.svg" style="width:50px"> French</a>
        </div>
    </div>
    <div class="container">
        <div class="row col-md-12 ">
            
            <table class="table table-striped ">
            
                    <?php

                    $is_current_employee = ($data['employee']['is_current_employee']=1)?'Yes':'No';
                            
                            echo '
                            <tr><td colspan=2 style="background-color:grey; color:white">General Informations</td></tr>
                            <tr><td>ID</td><td>'.$data['employee']['id'].'</td></tr>
                            <tr><td>Name</td><td>'.$data['employee']['name'].'</td></tr>
                            <tr><td>Email</td><td>'.$data['employee']['email'].'</td></tr>
                            <tr><td>Birth Date</td><td>'.$data['employee']['birthdate'].'</td></tr>
                            <tr><td>Phone</td><td>'.$data['employee']['phone'].'</td></tr>
                            <tr><td>SSN</td><td>'.$data['employee']['ssn'].'</td></tr>
                            <tr><td>Current</td><td>'.$is_current_employee.'</td></tr>
                            <tr><td>Address</td><td>'.$data['employee']['address'].'</td></tr>
                            </tr>
                            ';

                           
                            foreach ($data['employee']['info'] as $key => $row) 
                            {
                                
                                if ($row['employee_info_id']==1){
                                    $title = $data['lang']['locale']['titleIntroduction'];
                                } else if ($row['employee_info_id']==2){
                                    $title = $data['lang']['locale']['titleExperience'];
                                } else if ($row['employee_info_id']==3){
                                    $title = $data['lang']['locale']['titleEducation'];
                                }


                                if (isset($data['lang']['current'])) {
                                echo '
                                    <tr><td colspan=2 style="background-color:grey; color:white">'.$title.'</td></tr>
                                    <tr><td><strong>'.$title.' </strong><br><br><img src="img/'.$data['lang']['current'].'.svg" style="width:50px"></td><td>'.$row['info_'.$data['lang']['current'].''].'</td></tr>
                                    ';
                                } 
                            }
                    ?>
            </table>
        </div>
    </div>
</main>


